import type { NavItem, SiteConfig } from './types';

/** Defaults légers pour le boot — évite d'importer tout constants.ts au chargement initial. */
export const DEFAULT_NAV_ITEMS: NavItem[] = [
  { id: 'nav-2', name: 'Boutique', view: 'shop', order: 1, status: 'active', position: 'top', createdAt: '2024-01-01T00:00:00Z' },
  { id: 'nav-1', name: 'Accueil', view: 'home', order: 2, status: 'active', position: 'side', createdAt: '2024-01-01T00:00:00Z' },
  { id: 'nav-3', name: 'Lookbook', view: 'lookbook', order: 3, status: 'active', position: 'side', createdAt: '2024-01-01T00:00:00Z' },
  { id: 'nav-7', name: 'Blog Inspirations', view: 'blog', order: 4, status: 'active', position: 'side', createdAt: '2024-01-01T00:00:00Z' },
  { id: 'nav-10', name: 'FAQ', view: 'faq', order: 5, status: 'active', position: 'side', createdAt: '2024-01-01T00:00:00Z' },
  { id: 'nav-13', name: 'Contactez-nous', view: 'contact', order: 6, status: 'active', position: 'side', createdAt: '2024-01-01T00:00:00Z' },
  { id: 'nav-4', name: 'Sur Mesure', view: 'custom-order', order: 7, status: 'active', position: 'side', createdAt: '2024-01-01T00:00:00Z' },
  { id: 'nav-5', name: 'Compagnon Tricot', view: 'knitting-companion', order: 8, status: 'active', position: 'side', createdAt: '2024-01-01T00:00:00Z' },
  { id: 'nav-6', name: 'Générateur IA', view: 'pattern-generator', order: 9, status: 'active', position: 'side', createdAt: '2024-01-01T00:00:00Z' },
  { id: 'nav-8', name: 'Calculateur de Laine', view: 'calculator', order: 10, status: 'active', position: 'side', createdAt: '2024-01-01T00:00:00Z' },
  { id: 'nav-9', name: 'Calculateur de Volume', view: 'volume-calculator', order: 11, status: 'active', position: 'side', createdAt: '2024-01-01T00:00:00Z' },
  { id: 'nav-11', name: 'À propos', view: 'about', order: 12, status: 'active', position: 'side', createdAt: '2024-01-01T00:00:00Z' },
  { id: 'nav-11-5', name: 'Équipe', view: 'team', order: 13, status: 'active', position: 'side', createdAt: '2024-01-01T00:00:00Z' },
];

export const DEFAULT_SITE_CONFIG: SiteConfig = {
  id: 'global',
  primaryColor: '',
  accentColor: '',
  showAdBanner: false,
  adBannerText: '',
  loyaltyConfig: {
    pointsPerPurchase: 0,
    pointsPerReview: 0,
    badges: [],
    levels: [],
  },
  homeFeaturedProducts: [],
  homeFeaturedCategories: [],
  showSlider: false,
  sliderItems: [],
  customSections: [],
  maintenance: { isActive: false, message: '' },
  branding: { primaryColor: '', secondaryColor: '' },
  features: [],
  seo: {
    home: { title: '', description: '' },
    shop: { title: '', description: '' },
    contact: { title: '', description: '' },
    about: { title: '', description: '' },
    team: { title: '', description: '' },
    cart: { title: '', description: '' },
    wishlist: { title: '', description: '' },
    comparison: { title: '', description: '' },
    lookbook: { title: '', description: '' },
    'custom-order': { title: '', description: '' },
    'knitting-companion': { title: '', description: '' },
    'pattern-generator': { title: '', description: '' },
    blog: { title: '', description: '' },
    calculator: { title: '', description: '' },
    'volume-calculator': { title: '', description: '' },
    faq: { title: '', description: '' },
    loyalty: { title: '', description: '' },
  },
  hero: {
    title: '',
    description: '',
    backgroundImages: [],
    ctaText: '',
  },
  marqueeItems: [],
  newsletterPopup: {
    isActive: false,
    title: '',
    message: '',
    delay: 0,
    image: '',
  },
};
