import type { NavItem, SiteConfig } from './types';

/** Defaults légers pour le boot — évite d'importer tout constants.ts au chargement initial. */
export const DEFAULT_NAV_ITEMS: NavItem[] = [
  { id: 'nav-2', name: 'Boutique', view: 'shop', order: 1, status: 'active', position: 'top', createdAt: '2024-01-01T00:00:00Z' },
  { id: 'nav-1', name: 'Accueil', view: 'home', order: 2, status: 'active', position: 'side', createdAt: '2024-01-01T00:00:00Z' },
  { id: 'nav-3', name: 'Lookbook', view: 'lookbook', order: 3, status: 'active', position: 'side', createdAt: '2024-01-01T00:00:00Z' },
  { id: 'nav-4', name: 'Sur Mesure', view: 'custom-order', order: 4, status: 'active', position: 'side', createdAt: '2024-01-01T00:00:00Z' },
  { id: 'nav-5', name: 'Compagnon Tricot', view: 'knitting-companion', order: 5, status: 'active', position: 'side', createdAt: '2024-01-01T00:00:00Z' },
  { id: 'nav-6', name: 'Générateur IA', view: 'pattern-generator', order: 6, status: 'active', position: 'side', createdAt: '2024-01-01T00:00:00Z' },
  { id: 'nav-7', name: 'Blog Inspirations', view: 'blog', order: 7, status: 'active', position: 'side', createdAt: '2024-01-01T00:00:00Z' },
  { id: 'nav-8', name: 'Calculateur de Laine', view: 'calculator', order: 8, status: 'active', position: 'side', createdAt: '2024-01-01T00:00:00Z' },
  { id: 'nav-9', name: 'Calculateur de Volume', view: 'volume-calculator', order: 9, status: 'active', position: 'side', createdAt: '2024-01-01T00:00:00Z' },
  { id: 'nav-10', name: 'FAQ', view: 'faq', order: 10, status: 'active', position: 'side', createdAt: '2024-01-01T00:00:00Z' },
  { id: 'nav-11', name: 'À propos', view: 'about', order: 11, status: 'active', position: 'side', createdAt: '2024-01-01T00:00:00Z' },
  { id: 'nav-11-5', name: 'Équipe', view: 'team', order: 11.5, status: 'active', position: 'side', createdAt: '2024-01-01T00:00:00Z' },
  { id: 'nav-13', name: 'Contactez-nous', view: 'contact', order: 13, status: 'active', position: 'side', createdAt: '2024-01-01T00:00:00Z' },
];

export const DEFAULT_SITE_CONFIG: SiteConfig = {
  id: 'global',
  primaryColor: '#3E4A3D',
  accentColor: '#5C6B5A',
  showAdBanner: true,
  adBannerText: "🎉 Offre de lancement : Livraison gratuite à partir de 200 000 FCFA d'achat avec le code BIENVENUE",
  loyaltyConfig: {
    pointsPerPurchase: 10,
    pointsPerReview: 50,
    badges: [],
    levels: [
      { groupId: 'g1', minPoints: 0 },
      { groupId: 'g2', minPoints: 500 },
      { groupId: 'g3', minPoints: 2000 },
    ],
  },
  homeFeaturedProducts: ['p1', 'p-tech1', 'p12', 'p-tech2'],
  homeFeaturedCategories: ['1', '7', '6', '3'],
  showSlider: true,
  sliderItems: [
    { id: 's1', image: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?auto=format&fit=crop&q=75&w=960&fm=webp', title: 'Nouvelle Collection', subtitle: "L'alliance parfaite entre élégance et tendance" },
    { id: 's2', image: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&q=75&w=960&fm=webp', title: 'Boutique Premium', subtitle: 'Découvrez notre sélection exclusive' },
  ],
  customSections: [],
  maintenance: { isActive: false, message: 'Notre site est actuellement en maintenance.' },
  branding: { primaryColor: '#1A1A1A', secondaryColor: '#B85535' },
  features: [
    { iconName: 'Package', title: 'Qualité Premium', description: 'Laines 100% naturelles' },
    { iconName: 'Truck', title: 'Livraison Rapide', description: 'Offerte dès 200 000 FCFA' },
    { iconName: 'ShieldCheck', title: 'Paiement Sécurisé', description: 'Transaction 100% protégée' },
    { iconName: 'Heart', title: 'Fait avec Amour', description: 'Sélection artisanale' },
  ],
  seo: {
    home: { title: 'Laine et Déco - Boutique Artisanale', description: 'Découvrez notre sélection variée, laines de qualité et objets de décoration artisanaux.' },
    shop: { title: 'Boutique Laine et Déco', description: 'Explorez notre catalogue.' },
    contact: { title: 'Contactez Laine et Déco', description: 'Une question ? Notre équipe est à votre écoute.' },
    about: { title: 'À propos de Laine et Déco', description: 'Découvrez notre passion pour l\'artisanat.' },
    team: { title: 'Notre Équipe', description: 'Les talents derrière Laine et Déco.' },
    cart: { title: 'Mon Panier', description: 'Finalisez votre commande.' },
    wishlist: { title: 'Ma Wishlist', description: 'Vos articles favoris.' },
    comparison: { title: 'Comparateur', description: 'Comparez nos produits.' },
    lookbook: { title: 'Lookbook', description: 'Inspirations et styles.' },
    'custom-order': { title: 'Sur Mesure', description: 'Votre projet personnalisé.' },
    'knitting-companion': { title: 'Compagnon Tricot', description: 'Aide à vos projets.' },
    'pattern-generator': { title: 'Générateur IA', description: 'Créez vos motifs.' },
    blog: { title: 'Blog', description: 'Inspirations et conseils.' },
    calculator: { title: 'Calculateur', description: 'Calculez vos besoins.' },
    'volume-calculator': { title: 'Calculateur Volume', description: 'Calculez vos volumes.' },
    faq: { title: 'FAQ', description: 'Questions fréquentes.' },
    loyalty: { title: 'Points VIP', description: 'Programme fidélité.' },
  },
  hero: {
    title: 'Créez une atmosphère chic et authentique',
    description: "Une sélection unique de laines artisanales et de décoration d'exception.",
    backgroundImages: ['https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?auto=format&fit=crop&q=75&w=960&fm=webp'],
    ctaText: 'Découvrir la collection',
  },
  marqueeItems: [
    { id: 'm1', text: 'LIVRAISON OFFERTE DÈS 200 000 FCFA', iconName: 'Package' },
    { id: 'm2', text: 'NOUVELLE COLLECTION DISPONIBLE', iconName: 'Sparkles' },
    { id: 'm3', text: 'TRICOTÉ AVEC AMOUR', iconName: 'Heart' },
  ],
  newsletterPopup: {
    isActive: true,
    title: "Rejoignez la communauté de L'Atelier",
    message: 'Inscrivez-vous à notre newsletter pour recevoir nos conseils tricot et des offres exclusives.',
    delay: 5000,
    image: 'https://picsum.photos/seed/newsletter/800/1200',
  },
};
